#!/usr/bin/env python3
"""ops-console 子菜单同步：sites/ops-console.yaml → lib/menu.generated.ts

由 prebuild / predev hook 触发；也可手动跑：
  python3 scripts/sync-menu.py

SSOT：~/Dev/tools/configs/menus/sites/ops-console.yaml
消费者：components/section-nav.tsx import { ITEMS } from "@/lib/menu.generated"
"""
import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: 需要 PyYAML。安装：pip3 install pyyaml", file=sys.stderr)
    sys.exit(2)

REPO = Path(__file__).parent.parent
YAML = Path.home() / "Dev" / "tools" / "configs" / "menus" / "sites" / "ops-console.yaml"
OUT = REPO / "lib" / "menu.generated.ts"


def main():
    if not YAML.exists():
        print(f"ERROR: {YAML} not found", file=sys.stderr)
        sys.exit(1)
    cfg = yaml.safe_load(YAML.read_text(encoding="utf-8")) or {}
    items = cfg.get("items") or []

    lines = [
        "// AUTO-GENERATED from ~/Dev/tools/configs/menus/sites/ops-console.yaml",
        "// Edit the yaml; this file is regenerated by scripts/sync-menu.py (prebuild hook).",
        "",
        "export const ITEMS = [",
    ]
    for it in items:
        href = json.dumps(it["href"], ensure_ascii=False)
        label = json.dumps(it["label"], ensure_ascii=False)
        lines.append(f"  {{ href: {href}, label: {label} }},")
    lines.append("] as const")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO)} ({len(items)} items)")


if __name__ == "__main__":
    main()
