// Mirrored from ~/Dev/stations/website/lib/shared-footer.generated.ts via @tlz/menu-ssot sync-menu.
// AUTO-GENERATED from ~/Dev/tools/configs/menus/footer.yaml
// Edit the yaml; this file is regenerated by menus.py build-website-footer
// (镜像到 @tlz/menu-ssot via sync-menu).

export interface SiteFooterLink {
  label: string
  href: string
  icon?: 'github' | 'linkedin' | 'mail' | 'file'
  external?: boolean
}
export interface SiteFooterBrand {
  /** Template containing {year} placeholder, replaced at runtime. */
  copyright: string
}

export const SHARED_FOOTER_BRAND: SiteFooterBrand = {"copyright": "© {year} 曾田力"}

export const SHARED_FOOTER_LINKS: SiteFooterLink[] = [
  {
    "label": "主站",
    "href": "https://tianlizeng.cloud/",
    "icon": "file"
  },
  {
    "label": "联系",
    "href": "https://tianlizeng.cloud/contact",
    "icon": "mail",
    "external": true
  },
  {
    "label": "GitHub",
    "href": "https://github.com/zengtianli",
    "icon": "github",
    "external": true
  }
]
