// AUTO-GENERATED from ~/Dev/tools/configs/menus/sites/ops-console.yaml
// Edit the yaml; this file is regenerated by scripts/sync-menu.py (prebuild hook).

export const ITEMS = [
  { href: "/", label: "概览" },
  { href: "/services-health", label: "服务健康" },
  { href: "/auggie", label: "Auggie 索引" },
  { href: "/auggie/workspaces", label: "Workspaces" },
  { href: "/hammerspoon", label: "Hammerspoon" },
] as const
