import { existsSync, readFileSync } from "node:fs"
import path from "node:path"

// Site header is regenerated by `python3 ~/Dev/devtools/lib/tools/menus.py
// render-site-header --all -w` from ~/Dev/tools/configs/menus/sites/ops-console.yaml.
function loadSiteHeader(): string {
  const p = path.join(process.cwd(), "site-header.html")
  if (!existsSync(p)) return ""
  return readFileSync(p, "utf-8")
}

const HTML = loadSiteHeader()

export default function SiteHeader() {
  if (!HTML) return null
  return <div dangerouslySetInnerHTML={{ __html: HTML }} />
}
