[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0071e3"
backgroundColor = "#fbfbfd"
secondaryBackgroundColor = "#f5f5f7"
textColor = "#1d1d1f"
font = "sans serif"
